### PR TITLE
myget compatible build scripts

### PR DESCRIPTION
**Pull request by neutmute**
As discussed, upgraded solution to support myget automated publishes.
I was rather presumptuous and forked from #11 - so best review that first. 

This PR merges to develop to bring it up to date. So for a clean diff:
* Hopefully - approve #11
* Merge `master` to `develop`

Noteable changes
* Tweaked a couple of tests to make them run ok in a timezone outside of AEST
* Added .gitattributes to fix a crlf problem with myget.org
* gitlink support - pdb's with source links to this repo now packaged into nuget packages

### To configure develop build
* Setup a myget build service pointing at `develop` branch. 
* Set `Version format` to `1.0.1-CI-{0}` say
* Check *Automatically patch AssemblyInfo.cs / project.json / VISX manifest / package.json*

It should succeed.

### To configure master build
* Merge *develop* to *master*
* Setup a myget build service pointing at `master` branch. 
* Set `Version format` to `1.0.0.{0}` say
* Set `Build counter` to `1` (to not conflict with existing nuget if used version format above)
* Check *Automatically patch AssemblyInfo.cs / project.json / VISX manifest / package.json*
* Add an environment variable `nugetapikey` with your nuget.org key

* It should publish to nuget and automatically do so with every merge to master!

### CODE REVIEW

**Comment by simonpinn** [comment]
@neutmute dude - this is a huge PR! I think we may need to break a few things down or out, I had reviewed #11 which still had a few outstanding issues. It would be blind merge for me with this one. Good thing I know you well! I'll try and get a chance this week, any chance you could just put the build task as a PR on its own and we can work backwards?

**Comment by neutmute** [comment]
its not as big as it looks! The merge is a request to develop and not master - that is why it looks so large - because develop hasn't kept up with master.

So all you need to do is 
* Review #11 - cormac made his updates today. If it still needs work then this one can wait
* Merge the master #11 into develop
* Come back here and look at the diff and it will look sensible

I requested a merge to develop and not the up to date master because I figured that would be how you would manage preview releases. PRs would need to be merged into develop from now on.
Then you merge to master to automatically publish a release to nuget.

**Comment by simonpinn** [comment]
I did miss the destination of the merge, thanks dude - yeah I'll do that and review. Cheers.

**Comment by simonpinn** [comment]
Cool, that's healthier now and makes a bit more sense. Fix up the conflict and I'll be happy to pull it in.
thanks

**Comment by neutmute** [comment]
Cormac has fixed his merge conflict, so if that looks good and you merge #11 to master & develop, the remaining unrelated diffs in here will fall away.

Note that you wouldn't need to keep `AssemblyInfo.cs` up to date once you start using myget + `build.ps1` - the myget build holds the version info and revision counter similar to a TeamCity build.

**Comment by simonpinn** [comment]
:+1:

**Pull request merged**
