### PR TITLE
Split Attributes out into seperate assembly

### PR DESCRIPTION
**Pull request by ravensorb**
Added NuSpec file for new assembly
Added build scripts
Added comments to entire code base
Changed build folder to support build scripts

### CODE REVIEW

**Comment by simonpinn** [comment]
hey @ravensorb,

Appreciate the separation of the library, it's actually how it started out as two separate assemblies. I've been recommending that if you want unobtrusiveness then just use the fluent config, that way you don't need to include Neo4JClient or Extension in your POCO libraries. But a separate assembly would allow more choice.

I'd be all good with this PR if all the auto-generated commenting was removed, comment where required and comment arguments where there is ambiguity (which there is some), but not just generic comments.

Good to add the build scripts too. 

Are you currently using the library?

cheers

**Comment by ravensorb** [comment]
I had another idea if you are interested.  We can keep the split assemblies, but have only 1 Nuget package that only installs the Attributes assemblies in PCL type projects.  The benefit is, this supports the PCL concept, the downside is, it would include everything in a standard class library.  

Thoughts?

I'll clean up the comments and remove the "junk" ones tomorrow.  Do you want me to create a new pull request after that?

**Comment by simonpinn** [comment]
Hi Shawn,

Idea is good, and I’d be keener if Neo4jClient supported PCL, which probably makes it less useful.

I think a separate package that just contains the attributes would be fine, I’m happy for you to iterate over the current PR, PR’s are always a work in progress.

You really prefer the attributes over unobtrusive config? I’ve stopped using the attributes myself, since only the repo requires Neo4j and extensions.

cheers

**Comment by ravensorb** [comment]
Ok, I/'ll leave it is as separate packages right now.  As for using attributes vs fluent -- I like attributes for more complex models.  Right now, my model has about 20 different types of "nodes" or entities with around 14 "relationships".  For this many items, I find it actually simpler to use attributes :smile:

**Comment by ravensorb** [comment]
I updated the commit to include the removal of the comments.

**Comment by simonpinn** [comment]
Ok - I'm good with a separate assembly, but it should be Neo4jClient.Extension.Core or .Common so that anything in future can go in it.

There is a lot of noise in the PR, I'd be happier just splitting off the assembly and creating the extra nuspec, since that's all that needs to happen. The powershell scripts aren't really required, as well as the changes to debug/release output folder...

Sorry to do this, I understand if you want me to just do it myself! But I'd just create a new branch and simplify the actual changes that are happening.

thanks!

**Comment by simonpinn** [comment]
I've split the attributes into a separate project and nuspec, please let me know if all is as expected.

Thanks for raising the issue, and apologies for taking a while to get to it, had a few projects on.

cheers

**Pull request closed without merging**
